CATALOGO_AGRAVOS = [
    {
        "agravo": "Acidente de Trabalho Grave",
        "ficha_pdf": "DRT_Acidente_Trabalho_Grave.pdf",
        "cids": ["Y96"],
        "palavras": ["ACIDENTE", "TRABALHO", "GRAVE"],
        "campos": ["TIPO_ACID", "EVOLUCAO", "CAT", "LOCAL_ACID", "PART_CORP1", "CID_LESAO"],
    },
    {
        "agravo": "Acidente de Trabalho com Exposição a Material Biológico",
        "ficha_pdf": "ACIDENTE DE TRABALHO COM EXPOSIÇÃO À MATERIAL BIOLÓGICO.pdf",
        "cids": ["Z20"],
        "palavras": ["MATERIAL", "BIOLOGICO", "BIOLÓGICO", "EXPOSICAO", "EXPOSIÇÃO"],
        "campos": ["TP_EXPOS", "MATERIAL", "CIRC_ACID", "AGENTE", "FONTE", "EPI_LUVA"],
    },
    {
        "agravo": "Dengue/Chikungunya",
        "ficha_pdf": "DENGUE_CHIKUNGUNYA.pdf",
        "cids": ["A90", "A91", "A92"],
        "palavras": ["DENGUE", "CHIKUNGUNYA", "ARBOVIROSE"],
        "campos": ["CLASSI_FIN", "CRITERIO", "EVOLUCAO", "DT_CHIK_S1", "SOROTIPO"],
    },
    {
        "agravo": "Animais Peçonhentos",
        "ficha_pdf": "ANIMAIS PEÇONHENTOS.pdf",
        "cids": ["X20", "X21", "X22", "X23", "X24", "X25", "X26", "X27", "X28", "X29", "T63"],
        "palavras": ["PECONHENTO", "PEÇONHENTO", "SERPENTE", "ESCORPIAO", "ESCORPIÃO", "ARANHA"],
        "campos": ["TP_ACIDENT", "ANI_TIPO", "SERPENTE", "ARANHA", "LAGARTA", "ESCORPIAO"],
    },
    {
        "agravo": "Meningite",
        "ficha_pdf": "MENINGITE.pdf",
        "cids": ["A39", "G00", "G01", "G02", "G03"],
        "palavras": ["MENINGITE", "MENINGO"],
        "campos": ["CLASSI_FIN", "CRITERIO", "SOROGRUPO", "LCR", "HEMOCULT"],
    },
    {
        "agravo": "AIDS em Adulto",
        "ficha_pdf": "AIDS ADULTO.pdf",
        "cids": ["B24"],
        "palavras": ["AIDS", "HIV", "ADULTO", "13 ANOS OU MAIS"],
        "campos": ["ID_OCUPA_N", "ANT_RETRO", "TRANSFUS", "DROGA_INJ", "EVID_HIV"],
    },
    {
        "agravo": "AIDS em Menor de 13 anos",
        "ficha_pdf": "AIDS MENOR 13.pdf",
        "cids": ["B24"],
        "palavras": ["AIDS", "MENOR", "13"],
        "campos": ["ID_MAE", "ESC_MAE", "RACA_MAE", "TRAN_VERT", "TRANSFUS"],
    },
    {
        "agravo": "Criança Exposta ao HIV",
        "ficha_pdf": "CRIANÇA EXPOSTA AO HIV.pdf",
        "cids": ["Z20.6", "Z206"],
        "palavras": ["CRIANCA", "CRIANÇA", "EXPOSTA", "HIV"],
        "campos": ["ALEIT_MAT", "ALEIT_CRU", "PROFILAX", "HIV_MAE"],
    },
    {
        "agravo": "Gestante HIV",
        "ficha_pdf": "GESTANTE HIV.pdf",
        "cids": ["Z21", "O98"],
        "palavras": ["GESTANTE", "HIV"],
        "campos": ["PRE_NATAL", "SISPRENAT", "ANT_RETRO", "TP_PARTO", "EVOL_GRAV"],
    },
    {
        "agravo": "Atendimento Antirrábico Humano",
        "ficha_pdf": "ATENDIMENTO ANTIRRÁBICO HUMANO.pdf",
        "cids": ["Z20.3", "Z203"],
        "palavras": ["ANTIRRABICO", "ANTI-RABICO", "ANTI-RÁBICO", "RABICO", "RÁBICO"],
        "campos": ["ANTEC_TRA", "ESP_ANIMA", "TRAT_IND", "COND_ANIM", "FERIMENTO"],
    },
    {
        "agravo": "Raiva Humana",
        "ficha_pdf": "RAIVA HUMANA.pdf",
        "cids": ["A82", "A82.9", "A829"],
        "palavras": ["RAIVA", "HUMANA"],
        "campos": ["ESP_ANIMA", "HIDROFOBIA", "AEROFOBIA", "AGRESSIV", "VARIANTE"],
    },
    {
        "agravo": "Botulismo",
        "ficha_pdf": "BOTULISMO.pdf",
        "cids": ["A05.1", "A051"],
        "palavras": ["BOTULISMO"],
        "campos": ["DIPLOPIA", "DISFAGIA", "DISFONIA", "BOCA_SECA", "PT_PALPEB"],
    },
    {
        "agravo": "Cólera",
        "ficha_pdf": "CÓLERA.pdf",
        "cids": ["A00"],
        "palavras": ["COLERA", "CÓLERA"],
        "campos": ["DIARREIA", "DESIDRATA", "VIBRIO", "EVACUACOES", "SANGUE"],
    },
    {
        "agravo": "Coqueluche",
        "ficha_pdf": "COQUELUCHE.pdf",
        "cids": ["A37"],
        "palavras": ["COQUELUCHE"],
        "campos": ["TOSSE", "GUINCHO", "APNEIA", "VOMITOS", "DTP"],
    },
    {
        "agravo": "Difteria",
        "ficha_pdf": "DIFTERIA.pdf",
        "cids": ["A36"],
        "palavras": ["DIFTERIA"],
        "campos": ["PSEUDOMEM", "EDEMA_PESCO", "MIOCARDITE", "PALATO", "LARINGE"],
    },
    {
        "agravo": "Doença de Chagas Aguda",
        "ficha_pdf": "DOENÇA DE CHAGAS AGUDA.pdf",
        "cids": ["B57"],
        "palavras": ["CHAGAS"],
        "campos": ["TRIATOM", "VESTIGIO", "TCRUZI", "SOROLOG", "VIA_ORAL"],
    },
    {
        "agravo": "Epizootia",
        "ficha_pdf": "EPIZOOTIA.pdf",
        "cids": [],
        "palavras": ["EPIZOOTIA"],
        "campos": ["DT_EPIZOO", "ANIMAL", "COLETA", "MAT_COLETA", "SUSP_DIAG"],
    },
    {
        "agravo": "Esquistossomose",
        "ficha_pdf": "ESQUISTOSSOMOSE.pdf",
        "cids": ["B65"],
        "palavras": ["ESQUISTOSSOMOSE"],
        "campos": ["COPROSCOP", "TRATAMENTO", "FORMA_CLI", "COLECAO_H", "OVOS"],
    },
    {
        "agravo": "Febre Amarela",
        "ficha_pdf": "FEBRE AMARELA.pdf",
        "cids": ["A95"],
        "palavras": ["FEBRE", "AMARELA"],
        "campos": ["VACINA_FA", "EPIZOOTIA", "MOSQUITO", "ICTERICIA", "HEMORRAG"],
    },
    {
        "agravo": "Febre por Vírus do Nilo Ocidental",
        "ficha_pdf": "FEBRE POR VÍRUS DO NILO OCIDENTAL.pdf",
        "cids": ["A92.3", "A923"],
        "palavras": ["NILO", "OCIDENTAL"],
        "campos": ["VIAGEM", "CAVALO", "AVES", "TRANSFUS", "ALEIT_MAT"],
    },
    {
        "agravo": "Febre Tifoide",
        "ficha_pdf": "FEBRE TIFÓIDE.pdf",
        "cids": ["A01.0", "A010"],
        "palavras": ["TIFOIDE", "TIFÓIDE"],
        "campos": ["CONTATO", "AGUA", "ALIMENTO", "CONSTIPAC", "ROSEOLA"],
    },
    {
        "agravo": "Surto DTA",
        "ficha_pdf": "FICHA DE INVESTIGAÇÃO DE SURTO - DTA.pdf",
        "cids": [],
        "palavras": ["SURTO", "DTA", "ALIMENTO", "AGUA", "ÁGUA"],
        "campos": ["TP_NOT", "VEICULO", "DOENTES", "HOSPITAL", "OBITOS", "INCUBACAO"],
    },
    {
        "agravo": "Surto Geral",
        "ficha_pdf": "FICHA DE INVESTIGAÇÃO DE SURTO.pdf",
        "cids": [],
        "palavras": ["SURTO"],
        "campos": ["TP_NOT", "MODO_TRAN", "VEICULO", "LOCAL_OCOR", "DT_SURTO"],
    },
    {
        "agravo": "Ficha de Notificação Individual",
        "ficha_pdf": "FICHA DE NOTIFICAÇÃO.pdf",
        "cids": [],
        "palavras": ["NOTIFICACAO", "NOTIFICAÇÃO", "INDIVIDUAL"],
        "campos": ["NU_NOTIFIC", "DT_NOTIFIC", "ID_AGRAVO", "NM_PACIENT", "DT_SIN_PRI"],
    },
    {
        "agravo": "Ficha de Notificação/Conclusão",
        "ficha_pdf": "FICHA DE NOTIFICAÇÃO_CONCLUSÃO.pdf",
        "cids": [],
        "palavras": ["CONCLUSAO", "CONCLUSÃO"],
        "campos": ["CLASSI_FIN", "CRITERIO", "EVOLUCAO", "DT_ENCERRA", "DT_OBITO"],
    },
    {
        "agravo": "Hanseníase",
        "ficha_pdf": "HANSENÍASE.pdf",
        "cids": ["A30"],
        "palavras": ["HANSENIASE", "HANSENÍASE"],
        "campos": ["NU_LESOES", "CLASS_OP", "MODO_ENTR", "MODO_DETEC", "ESQ_INI"],
    },
    {
        "agravo": "Hantavirose",
        "ficha_pdf": "HANTAVIROSE.pdf",
        "cids": ["B33.4", "B334"],
        "palavras": ["HANTAVIROSE", "HANTA"],
        "campos": ["RATO", "SILVESTRE", "GALPAO", "INSUF_RESP", "EDEMA_PULM"],
    },
    {
        "agravo": "Hepatites Virais",
        "ficha_pdf": "HEPATITES VIRAIS.pdf",
        "cids": ["B15", "B16", "B17", "B18", "B19"],
        "palavras": ["HEPATITE", "HEPATITES"],
        "campos": ["HEPATITE_A", "HEPATITE_B", "HEPATITE_C", "VACINA_HEP", "HBSAG"],
    },
    {
        "agravo": "Influenza Humana por Novo Subtipo",
        "ficha_pdf": "INFLUENZA HUMANA POR NOVO SUBTIPO (PANDÊMICO).pdf",
        "cids": ["J11"],
        "palavras": ["INFLUENZA", "NOVO", "SUBTIPO", "PANDEMICO", "PANDÊMICO"],
        "campos": ["VACINA_GRI", "CONT_AVES", "DESLOCAM", "TOSSE", "DISPNEIA"],
    },
    {
        "agravo": "Intoxicação Exógena",
        "ficha_pdf": "INTOXICAÇÃO EXÓGENA.pdf",
        "cids": ["T65.9", "T659", "T65"],
        "palavras": ["INTOXICACAO", "INTOXICAÇÃO", "EXOGENA", "EXÓGENA"],
        "campos": ["AGENTE_TOX", "LOCAL_EXPO", "CIRCUNSTAN", "ATIVIDADE", "EVOLUCAO"],
    },
    {
        "agravo": "Leishmaniose Tegumentar Americana",
        "ficha_pdf": "LEISHMANIOSE TEGUMENTAR AMERICANA.pdf",
        "cids": ["B55.1", "B551"],
        "palavras": ["LEISHMANIOSE", "TEGUMENTAR", "AMERICANA"],
        "campos": ["LESAO", "PARASITO", "HISTOPATO", "FORMA", "DROGA_INI"],
    },
    {
        "agravo": "Leishmaniose Visceral",
        "ficha_pdf": "LEISHMANIOSE VISCERAL.pdf",
        "cids": ["B55.0", "B550"],
        "palavras": ["LEISHMANIOSE", "VISCERAL"],
        "campos": ["FEBRE", "BACO", "FIGADO", "PARASITO", "IMUNOLOGICO"],
    },
    {
        "agravo": "Leptospirose",
        "ficha_pdf": "LEPTOSPIROSE.pdf",
        "cids": ["A27"],
        "palavras": ["LEPTOSPIROSE"],
        "campos": ["ENCHENTE", "ROEDORES", "ICTERICIA", "MIALGIA", "PANTURRILHA"],
    },
    {
        "agravo": "Malária",
        "ficha_pdf": "MALÁRIA.pdf",
        "cids": ["B50", "B51", "B52", "B53", "B54"],
        "palavras": ["MALARIA", "MALÁRIA"],
        "campos": ["LAMINA", "PARASITEMIA", "RESULT_EXA", "PLASMODIUM", "CRUZES"],
    },
    {
        "agravo": "Paralisia Flácida Aguda/Poliomielite",
        "ficha_pdf": "PARALISIA FLÁCIDA AGUDA_POLIOMIELITE.pdf",
        "cids": ["A80", "A80.9", "A809"],
        "palavras": ["PARALISIA", "FLACIDA", "FLÁCIDA", "POLIOMIELITE", "PFA"],
        "campos": ["DEF_MOTORA", "VAC_POLIO", "FORCA_MUSC", "TONUS", "REFLEXOS"],
    },
    {
        "agravo": "Peste",
        "ficha_pdf": "PESTE.pdf",
        "cids": ["A20", "A20.9", "A209"],
        "palavras": ["PESTE"],
        "campos": ["GANGLO", "PULMONAR", "BACTERIO", "SOROLOGIA", "CONTROLE"],
    },
    {
        "agravo": "Rotavírus",
        "ficha_pdf": "ROTAVÍRUS.pdf",
        "cids": ["A08.0", "A080"],
        "palavras": ["ROTAVIRUS", "ROTAVÍRUS"],
        "campos": ["DIARREIA", "VOMITOS", "FEZES", "GENOTIPO", "VAC_ROT"],
    },
    {
        "agravo": "Sífilis Congênita",
        "ficha_pdf": "SÍFILIS CONGÊNITA.pdf",
        "cids": ["A50", "A50.9", "A509"],
        "palavras": ["SIFILIS", "SÍFILIS", "CONGENITA", "CONGÊNITA"],
        "campos": ["IDADE_MAE", "PRE_NATAL", "TRAT_MAE", "TITULO", "PARC_TRAT"],
    },
    {
        "agravo": "Sífilis em Gestante",
        "ficha_pdf": "SÍFILIS EM GESTANTE.pdf",
        "cids": ["O98", "A53"],
        "palavras": ["SIFILIS", "SÍFILIS", "GESTANTE"],
        "campos": ["PRE_NATAL", "CLASS_CLI", "TESTE_TREP", "ESQUEMA", "PARC_TRAT"],
    },
    {
        "agravo": "Tétano Acidental",
        "ficha_pdf": "TÉTANO ACIDENTAL.pdf",
        "cids": ["A35"],
        "palavras": ["TETANO", "TÉTANO", "ACIDENTAL"],
        "campos": ["CAUSA", "LOCAL_LES", "VACINA", "TRISMO", "OPISTOTONO"],
    },
    {
        "agravo": "Tétano Neonatal",
        "ficha_pdf": "TÉTANO NEONATAL.pdf",
        "cids": ["A33"],
        "palavras": ["TETANO", "TÉTANO", "NEONATAL"],
        "campos": ["CONS_PREN", "PARTO", "COTO", "TRISMO", "MAMAR"],
    },
    {
        "agravo": "Tuberculose",
        "ficha_pdf": "TUBERCULOSE.pdf",
        "cids": ["A15", "A16", "A16.9", "A169"],
        "palavras": ["TUBERCULOSE"],
        "campos": ["TIPO_ENTRA", "FORMA", "BACILOSC", "CULTURA", "HIV", "TRATAMENTO"],
    },
    {
        "agravo": "Violência Interpessoal/Autoprovocada",
        "ficha_pdf": "VIOLÊNCIA INTERPESSOAL_AUTOPROVOCADA.pdf",
        "cids": ["Y09"],
        "palavras": ["VIOLENCIA", "VIOLÊNCIA", "AUTOPROVOCADA", "INTERPESSOAL"],
        "campos": ["LOCAL_OCOR", "LES_AUTOP", "VIOL_FISIC", "VIOL_SEXU", "MEIO_AGRE", "AUTOR"],
    },
    {
        "agravo": "Câncer Relacionado ao Trabalho",
        "ficha_pdf": "CÂNCER RELACIONADO AO TRABALHO.pdf",
        "cids": ["C"],
        "palavras": ["CANCER", "CÂNCER", "TRABALHO"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "TEMPO_TRAB", "EMP_TERCE"],
    },
    {
        "agravo": "Dermatoses Ocupacionais",
        "ficha_pdf": "DERMATOSES OCUPACIONAIS.pdf",
        "cids": ["L"],
        "palavras": ["DERMATOSE", "DERMATOSES", "OCUPACIONAL"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "AGENTE_RISCO", "REGIME"],
    },
    {
        "agravo": "LER/DORT",
        "ficha_pdf": "LER_DORT.pdf",
        "cids": ["M"],
        "palavras": ["LER", "DORT"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "REGIME", "AGRAV_ASSOC"],
    },
    {
        "agravo": "PAIR",
        "ficha_pdf": "PAIR.pdf",
        "cids": ["H83"],
        "palavras": ["PAIR", "AUDITIVA"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "TEMPO_EXPO", "REGIME"],
    },
    {
        "agravo": "Pneumoconioses",
        "ficha_pdf": "PNEUMOCONIOSES.pdf",
        "cids": ["J60", "J61", "J62", "J63", "J64"],
        "palavras": ["PNEUMOCONIOSE", "PNEUMOCONIOSES"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "TEMPO_EXPO", "REGIME"],
    },
    {
        "agravo": "Transtornos Mentais Relacionados ao Trabalho",
        "ficha_pdf": "TRANSTORNOS MENTAIS RELACIONADOS AO TRABALHO.pdf",
        "cids": ["F43"],
        "palavras": ["TRANSTORNO", "MENTAL", "TRABALHO"],
        "campos": ["ID_OCUPA_N", "SIT_TRAB", "CNAE", "TEMPO_TRAB", "REGIME"],
    },
]
