CATALOGO_AGRAVOS = {
    "ACBIONET": "Acidente de Trabalho com Exposição a Material Biológico",
    "ACGRANET": "Acidente de Trabalho Grave",
    "AGRAVNET": "Agravos Relacionados ao Trabalho",
    "AIDSANET": "AIDS Adulto",
    "AIDSCNET": "AIDS Criança",
    "ANIMPNET": "Acidente por Animais Peçonhentos",
    "ANTRANET": "Atendimento Antirrábico Humano",
    "BOTUNET": "Botulismo",
    "CANCENET": "Câncer Relacionado ao Trabalho",
    "CHAGANET": "Doença de Chagas",
    "CHIKON": "Chikungunya",
    "COLENET": "Cólera",
    "COQUENET": "Coqueluche",
    "DENGNET": "Dengue",
    "DENGON": "Dengue",
    "DERMANET": "Dermatoses Ocupacionais",
    "DIFTENET": "Difteria",
    "DTANET": "Doenças Transmitidas por Alimentos",
    "EPIZONET": "Epizootia",
    "ESPORONET": "Esporotricose",
    "ESQUINET": "Esquistossomose",
    "EXANTNET": "Doenças Exantemáticas",
    "HANSNET": "Hanseníase",
    "HANTANET": "Hantavirose",
    "HEPANET": "Hepatites Virais",
    "HIVGENET": "HIV Gestante",
    "IEXOGNET": "Intoxicação Exógena",
    "INFLUNET": "Influenza/SRAG",
    "LEISHNET": "Leishmaniose Visceral",
    "LEPTONET": "Leptospirose",
    "LERNET": "LER/DORT",
    "LTANET": "Leishmaniose Tegumentar Americana",
    "MALANET": "Malária",
    "MENINNET": "Meningite",
    "MENTANET": "Transtorno Mental Relacionado ao Trabalho",
    "NEXCNET": "Notificação de Exposição a Contaminantes",
    "NILONET": "Febre do Nilo",
    "NINDINET": "Notificação Individual",
    "PAIRNET": "PAIR",
    "PESTENET": "Peste",
    "PFANET": "Paralisia Flácida Aguda",
    "PNEUMNET": "Pneumoconioses",
    "RAIVANET": "Raiva Humana",
    "ROTANET": "Rotavírus",
    "SIFGENET": "Sífilis em Gestante",
    "SIFICNET": "Sífilis Congênita",
    "SRCNET": "Síndrome da Rubéola Congênita",
    "TETACNET": "Tétano Acidental",
    "TETANNET": "Tétano Neonatal",
    "TRACONET": "Tracoma",
    "TUBENET": "Tuberculose",
    "VIOLENET": "Violência Interpessoal/Autoprovocada",
    "ZIKANET": "Zika",
}


def identificar_por_nome_arquivo(nome_arquivo):
    nome = str(nome_arquivo).upper()

    for chave, agravo in CATALOGO_AGRAVOS.items():
        if chave in nome:
            return agravo

    return None
