[server]
maxUploadSize = 500
maxMessageSize = 500

[theme]
base = "light"
primaryColor = "#009B5A"
backgroundColor = "#F7FAF8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101820"
font = "sans serif"
