[theme]
primaryColor = "#00ED64"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#E1E8ED"
textColor = "#101820"
font = "sans serif"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false
