[server]
maxUploadSize = 500
maxMessageSize = 500

[theme]
base = "dark"
primaryColor = "#00ED64"
backgroundColor = "#041C32"
secondaryBackgroundColor = "#0B2B4A"
textColor = "#FFFFFF"
font = "sans serif"
